name: C++ Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgsl-dev libcfitsio-dev mpich libccfits-dev cmake g++

    - name: Compile
      run: |
        mkdir -p build
        cd build
        cmake ..
        make

